#!/usr/bin/python

import os
import glob
from sys import version_info

print("shraddha")
#print(version_info)


#!!!!!!!!!!!!! How to capture inputs !!!!!!!!!!!!!!!!!!!
# makemei will hold the variable or the input from screen
#makemei = raw_input("What is the sum are you looking /n")
# !!!!!!!!!!! Capture input ends !!!!!!!!!!!!!!!!!!!!!!!


#@@@@@@@@@@@@@@ File operations commands here @@@@@@@@@@@@@@@@@@@
#os.chdir('/Users/ychicago/getme') # change directory
#filelist=glob.glob("*.*")         # Getting list of files from the directory

#with open ("/tmp/filelist","w") as filevar:  # Opening a file for writing
#     for i in filelist:
#                print(i)
#                cmd="wc - l "+ i
#                print(cmd)
#                os.system(cmd)
#                filevar.write(i)
#                filevar.write("\n")
# @@@@@@@@@@@@@ File operations ends here @@@@@@@@@@@@@@@@@@@@@@

########## Fibonacci list of numbers ###########################
#fiblist=[0,1]
#for i in range(1,9):
#       print(i)
#       print 1000 , fiblist[i-1],fiblist[i-2]
#       j=fiblist[i] + fiblist[i-1]
#       print j
#       fiblist.append(j)
#
#print fiblist
####### Fibonacci list ends here ############################
